import { createBlock } from "./blocks/defaults";
import type { Block, PageContent } from "./types";

// Each template is a function returning seed blocks for a theme.
// New IDs are generated by createBlock so blocks are unique per page.
type TemplateFn = () => { name: string; theme: PageContent["theme"]; blocks: Block[] };

const set = (b: Block, patch: Partial<Block>): Block => ({ ...b, ...patch, content: { ...b.content, ...(patch.content || {}) }, style: { ...b.style, ...(patch.style || {}) } });

const baseSite = (overrides: { brand: string; title: string; subtitle: string; accent: string; bg: string }): Block[] => [
  set(createBlock("navbar"), { content: { brand: overrides.brand } as any, style: { background: "#ffffff", color: "#0f172a" } }),
  set(createBlock("hero"), {
    content: { title: overrides.title, subtitle: overrides.subtitle, eyebrow: overrides.brand, ctaText: "Get Started", ctaLink: "#" } as any,
    style: { background: overrides.bg, color: "#ffffff", textAlign: "center", paddingTop: "112px", paddingBottom: "112px" },
  }),
  createBlock("about"),
  createBlock("services"),
  createBlock("gallery"),
  createBlock("testimonial"),
  createBlock("pricing"),
  createBlock("contact"),
  set(createBlock("footer"), { content: { text: `© 2026 ${overrides.brand}. All rights reserved.` } as any }),
];

export const THEME_TEMPLATES: Record<string, TemplateFn> = {
  freelancer: () => ({
    name: "Freelancer Site",
    theme: { primaryColor: "#dc2626", fontFamily: "Inter, sans-serif", background: "#ffffff" },
    blocks: baseSite({ brand: "Freelancer", title: "I build brands that ship", subtitle: "Independent designer + developer for hire.", accent: "#dc2626", bg: "linear-gradient(135deg,#0f172a 0%,#581c87 100%)" }),
  }),
  "small-business": () => ({
    name: "Small Business Site",
    theme: { primaryColor: "#0ea5e9", fontFamily: "Inter, sans-serif", background: "#f8fafc" },
    blocks: baseSite({ brand: "Acme Co.", title: "Local. Trusted. Reliable.", subtitle: "Serving our community since 2010.", accent: "#0ea5e9", bg: "linear-gradient(135deg,#0c4a6e 0%,#0284c7 100%)" }),
  }),
  "prd-graphic-designer": () => ({
    name: "Graphic Designer Site",
    theme: { primaryColor: "#ec4899", fontFamily: "Inter, sans-serif", background: "#ffffff" },
    blocks: baseSite({ brand: "Designer", title: "Visual stories that move.", subtitle: "Branding, illustration & art direction.", accent: "#ec4899", bg: "linear-gradient(135deg,#831843 0%,#db2777 100%)" }),
  }),
  "prd-photographer": () => ({
    name: "Photographer Site",
    theme: { primaryColor: "#f59e0b", fontFamily: "Georgia, serif", background: "#fafaf9" },
    blocks: baseSite({ brand: "Studio", title: "Capturing moments, crafting memories.", subtitle: "Editorial, wedding & lifestyle photography.", accent: "#f59e0b", bg: "linear-gradient(135deg,#1c1917 0%,#44403c 100%)" }),
  }),
  "prd-digital-marketer": () => ({
    name: "Marketer Site",
    theme: { primaryColor: "#3b82f6", fontFamily: "Inter, sans-serif", background: "#ffffff" },
    blocks: baseSite({ brand: "Growth Lab", title: "Performance marketing that scales.", subtitle: "Data-driven growth for ambitious teams.", accent: "#3b82f6", bg: "linear-gradient(135deg,#1e3a8a 0%,#3b82f6 100%)" }),
  }),
  biography: () => ({
    name: "Personal Bio",
    theme: { primaryColor: "#7c3aed", fontFamily: "Georgia, serif", background: "#ffffff" },
    blocks: [
      set(createBlock("hero"), {
        content: { title: "Your Name", subtitle: "Writer · Speaker · Storyteller", eyebrow: "Hello, I'm", ctaText: "Read my story", ctaLink: "#about" } as any,
        style: { background: "linear-gradient(135deg,#1e1b4b 0%,#7c3aed 100%)", color: "#ffffff", textAlign: "center", paddingTop: "128px", paddingBottom: "128px" },
      }),
      createBlock("about"),
      createBlock("gallery"),
      createBlock("contact"),
      createBlock("footer"),
    ],
  }),
  "custom-code": () => ({
    name: "Custom HTML Page",
    theme: { primaryColor: "#dc2626", fontFamily: "Inter, sans-serif", background: "#ffffff" },
    blocks: [createBlock("customCode")],
  }),
};

export const getThemeTemplate = (themeId: string): { name: string; theme: PageContent["theme"]; blocks: Block[] } => {
  const fn = THEME_TEMPLATES[themeId];
  if (fn) return fn();
  // Fallback for admin: themes or unknown
  return THEME_TEMPLATES.freelancer();
};
