// List of common disposable/temporary email domains
// This list covers the most popular temporary email providers

export const DISPOSABLE_EMAIL_DOMAINS = [
  // Popular temp mail services
  'tempmail.com',
  'temp-mail.org',
  'guerrillamail.com',
  'guerrillamail.org',
  'guerrillamail.net',
  'guerrillamail.biz',
  'guerrillamail.de',
  'sharklasers.com',
  'grr.la',
  'mailinator.com',
  'mailinator2.com',
  'mailinater.com',
  'mailinator.net',
  'mailinator.org',
  '10minutemail.com',
  '10minutemail.net',
  '10minutemail.org',
  '10minmail.com',
  'minutemail.com',
  'yopmail.com',
  'yopmail.fr',
  'yopmail.net',
  'throwawaymail.com',
  'throwaway.email',
  'getnada.com',
  'nada.email',
  'tempail.com',
  'fakeinbox.com',
  'fakemailgenerator.com',
  'dispostable.com',
  'mailnesia.com',
  'maildrop.cc',
  'mailcatch.com',
  'meltmail.com',
  'moakt.com',
  'mohmal.com',
  'mytrashmail.com',
  'trashmail.com',
  'trashmail.net',
  'trashmail.org',
  'trashemail.de',
  'wegwerfmail.de',
  'wegwerfmail.net',
  'wegwerfmail.org',
  'spambox.us',
  'spamfree24.org',
  'spamgourmet.com',
  'spam4.me',
  'spamex.com',
  'tempinbox.com',
  'temp.email',
  'tempr.email',
  'tempsky.com',
  'emailondeck.com',
  'getairmail.com',
  'dropmail.me',
  'mailsac.com',
  'crazymailing.com',
  'burnermail.io',
  'burneremail.com',
  'mailnator.com',
  'mailtemp.net',
  'tempmailo.com',
  'mailpoof.com',
  'hide.biz.st',
  'hidzz.com',
  'superrito.com',
  'supere.ml',
  'emailfake.com',
  'fakemail.net',
  'fakemailgenerator.net',
  'inboxkitten.com',
  'jetable.org',
  'jetable.com',
  'jetable.fr.nf',
  'koszmail.pl',
  'lroid.com',
  'mintemail.com',
  'safetymail.info',
  'spamobox.com',
  'tmpmail.org',
  'tmpmail.net',
  'tmpeml.info',
  'tmails.net',
  'anonymmail.net',
  'tempmailaddress.com',
  'mail-temp.com',
  'discard.email',
  'discardmail.com',
  'discardmail.de',
  'spambog.com',
  'spambog.de',
  'spambog.ru',
  'kasmail.com',
  'armyspy.com',
  'cuvox.de',
  'dayrep.com',
  'einrot.com',
  'fleckens.hu',
  'gustr.com',
  'jourrapide.com',
  'rhyta.com',
  'superrito.com',
  'teleworm.us',
  'trbvn.com',
  // Additional common ones
  'mailforspam.com',
  'sofimail.com',
  'spam.la',
  'spaml.de',
  'spaml.com',
  'spamherelots.com',
  'binkmail.com',
  'bobmail.info',
  'chammy.info',
  'devnullmail.com',
  'dontreg.com',
  'dontsendmespam.de',
  'e4ward.com',
  'emailias.com',
  'emailsensei.com',
  'emailtemporanea.com',
  'emailtemporanea.net',
  'emailtemporar.ro',
  'emailthe.net',
  'emailtmp.com',
  'example.com',
  'fasttempmail.com',
  'filzmail.com',
  'flyspam.com',
  'garbagecollector.org',
  'garbagemail.org',
  'gishpuppy.com',
  'great-host.in',
  'greensloth.com',
  'haltospam.com',
  'hopemail.biz',
  'ichimail.com',
  'incognitomail.com',
  'incognitomail.org',
  'ipoo.org',
  'irish2me.com',
  'jetable.net',
  'klassmaster.com',
  'klassmaster.net',
  'klzlv.com',
  'kulturbetrieb.info',
  'kurzepost.de',
  'lifebyfood.com',
  'link2mail.net',
  'litedrop.com',
  'lookugly.com',
  'lopl.co.cc',
  'lortemail.dk',
  'lovemeleaveme.com',
  'lr78.com',
  'maboard.com',
  'mail.by',
  'mail.mezimages.net',
  'mailbidon.com',
  'mailblocks.com',
  'mailchop.com',
  'mailclean.com',
  'maileater.com',
  'mailexpire.com',
  'mailfreeonline.com',
  'mailguard.me',
  'mailin8r.com',
  'mailinater.com',
  'mailmate.com',
  'mailmetrash.com',
  'mailmoat.com',
  'mailnull.com',
  'mailscrap.com',
  'mailshell.com',
  'mailsiphon.com',
  'mailslite.com',
  'mailtemporaire.fr',
  'mailzilla.com',
  'mailzilla.org',
];

/**
 * Check if an email domain is a known disposable/temporary email provider
 * @param email The email address to check
 * @returns true if the email is from a disposable provider
 */
export function isDisposableEmail(email: string): boolean {
  if (!email || !email.includes('@')) return false;
  
  const domain = email.split('@')[1]?.toLowerCase();
  if (!domain) return false;
  
  return DISPOSABLE_EMAIL_DOMAINS.includes(domain);
}

/**
 * List of allowed email domains (whitelist approach)
 * Only these domains are allowed for signup
 */
export const ALLOWED_EMAIL_DOMAINS = [
  'gmail.com',
  'googlemail.com',
];

/**
 * Check if an email is from an allowed domain
 * @param email The email address to check
 * @returns true if the email is from an allowed domain
 */
export function isAllowedEmailDomain(email: string): boolean {
  if (!email || !email.includes('@')) return false;
  
  const domain = email.split('@')[1]?.toLowerCase();
  if (!domain) return false;
  
  return ALLOWED_EMAIL_DOMAINS.includes(domain);
}
